### list all the messages

### get list of messages
GET http://localhost:3000/messages

### post message 

POST  http://localhost:3000/messages?validate=true&hello=rishi
Content-Type: application/json

{
    "content":"null"
}


### get message with a id
GET http://localhost:3000/messages/1212122



### signup check
POST  http://localhost:3000/users/signup?validate=true&hello=rishi
Content-Type: application/json

{
    "email":"2abc@123as.com",
    "password":"pasdasdasd"
}

### get user with a id
GET http://localhost:3000/users/1



### get all users
GET http://localhost:3000/users?email=pasdasdasd12@test.com


### delete a user
DELETE http://localhost:3000/users/1


### patch the user with our request body
PATCH  http://localhost:3000/users/2
Content-Type: application/json

{
  
    "email":"pasdasdasd12@test.com"
}


### report 
POST http://localhost:3000/reports
content-type: application/json

{
  "price":2000,
  "make":"sdasd12",
  "model":"genx",
  "year":2023,
  "lat":17,
  "lng":18,
  "mileage":30,
  "userId":1
}